#!/bin/sh
set -eu

cd "$(dirname "$0")"

: ${DESTDIR:=}
: ${PREFIX:="/usr/local"}

SCRIPTS_DIR="${DESTDIR}$PREFIX/share/one-context/scripts"
CONF_DIR="$DESTDIR/etc/one-context.d"

install -Dv -m 755 init.d/vmcontext "$DESTDIR"/etc/init.d/vmcontext

find scripts/ -type f ! -name '*.sh' | while read path; do
	install -Dv -m 755 $path "$SCRIPTS_DIR"/$(basename $path)
done

for path in scripts/*.sh; do
	install -Dv -m 644 $path "$SCRIPTS_DIR"/$(basename $path)
done
