= OpenNebula Contextualization / OpenRC
:proj-name: one-context
:gh-name: jirutka/{proj-name}

This project provides “contextualization” scripts for https://alpinelinux.org[Alpine Linux] and https://gentoo.org[Gentoo] virtual machines running on http://opennebula.org[OpenNebula].

The scripts are inspired by the official scripts from https://github.com/OpenNebula/addon-context-linux[addon-context-linux], but rewritten from scratch to be more readable, robust and fully POSIX compatible.
This is _not_ yet another fork of these poor official scripts.


== Requirements

* POSIX-compatible shell (e.g. ash, bash, dash)
* https://wiki.gentoo.org/wiki/OpenRC[OpenRC]
* blkid from https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git[util-linux] (for OpenRC runscript)
* btrfs utility and/or resize2fs from http://e2fsprogs.sourceforge.net[e2fsprogs] (only for growfs script)
* https://wiki.gentoo.org/wiki/Netifrc[Netifrc] or `ifup` (only for network scripts)
* kernel with support for mounting CD-ROM with ISO 9660 filesystem footnote:[This is the way how OpenNebula passes configuration variables into VM.]


== Installation

=== Alpine Linux

. Install https://pkgs.alpinelinux.org/packages?name={proj-name}[{proj-name}] from the Alpine’s main repository:
+
[source, sh, subs="+attributes"]
apk add {proj-name}


=== Manually

. Clone this repository and jump in:
+

[source, sh, subs="+attributes"]
git clone https://github.com/{gh-name}.git
cd one-context

. Install init script, contextualization scripts and symlinks (you may need to run this with sudo)…
+
[source, sh]
./install
+
You may use variables `DESTDIR` and `PREFIX` to specify the target directories.

. `rc-update add vmcontext boot`


=== Directory Structure

The scripts are installed into `/usr/share/one-context/scripts` (depends on `DESTDIR` and `PREFIX` variables, see above) and symlinked into `/etc/one-context.d` with a numeric prefix to specify the execution order.
The runscript is installed into `/etc/init.d/vmcontext`.


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
