= OpenNebula Contextualization / OpenRC

This project provides “contextualization” scripts for https://alpinelinux.org[Alpine Linux] and https://gentoo.org[Gentoo] virtual machines running on http://opennebula.org[OpenNebula].

The scripts are inspired by the official scripts from https://github.com/OpenNebula/addon-context-linux[addon-context-linux], but rewritten from scratch to be more readable, robust and fully POSIX compatible.
This is _not_ yet another fork of these poor official scripts.


== Requirements

* POSIX-compatible shell (e.g. ash, bash, dash)
* https://wiki.gentoo.org/wiki/OpenRC[OpenRC]
* https://wiki.gentoo.org/wiki/Netifrc[Netifrc] or `ifup` (only for network scripts)
* kernel with support for mounting CD-ROM with ISO 9660 filesystem footnote:[This is the way how OpenNebula passes configuration variables into VM.]


== Installation

=== Alpine Linux

. Add `edge/community` repository (e.g. http://dl-cdn.alpinelinux.org/alpine/edge/community) to `/etc/apk/repositories`, if you don’t have it yet, and run `apk update`.
. Install https://pkgs.alpinelinux.org/package/edge/community/x86_64/qemu-init-script[one-context]:
+
    apk add one-context


=== Gentoo

. Add https://github.com/cvut/gentoo-overlay[CTU’s Gentoo Overlay] to your repos.conf or Layman (read https://github.com/cvut/gentoo-overlay#usage[howto]).
. `emerge -av app-admin/one-context`
. `rc-update add vmcontext boot`


=== Manually

. Clone this repository and jump in:
+
    git clone https://github.com/jirutka/one-context.git
    cd one-context

. Install runscript, contextualization scripts and symlinks (you may need to run this with sudo)…
+
    ./install
+
You may use variables `DESTDIR` and `PREFIX` to specify the target directories.

. `rc-update add vmcontext boot`


=== Directory Structure

The scripts are installed into `/usr/share/one-context/scripts` (depends on `DESTDIR` and `PREFIX` variables, see above) and symlinked into `/etc/one-context.d` with a numeric prefix to specify the execution order.
The runscript is installed into `/etc/init.d/vmcontext`.


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
