#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/utils.sh

name="$(hostname)"
update_config '/etc/hosts' "$(readlink -f $0)" <<-EOF
	127.0.0.1	${name}.local ${name} localhost
	::1		${name}.local ${name} localhost
EOF
