#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/utils.sh

update_config '/etc/hosts' "$(readlink -f $0)" <<-EOF
	127.0.0.1	$(hostname -f) $(hostname -s) localhost
	::1		$(hostname -f) $(hostname -s) localhost
EOF
